package org.swg.swiftgroups_app.CGAPI.Profile

import kotlinx.serialization.Serializable


@Serializable
data class ProfileDataItem(
    val QRCode: Int,
    val accountType: String,
    val accountTypeLookup: Int,
    val accountTypeType: String,
    val accountTypeValue: String,
    val address: String?,
    val address2: String?,
    val allowChat: Int,
    val bio: String,
    val bio_only: String,
    val bookmarked: Int,
    val chatToken: String,
    val city: String?,
    val clubName: String?,
    val color: String?,
    val companyName: String?,
    val connectionStatus: Int,
    val country: String?,
    val currentAddress: String,
    val currentCity: String,
    val currentCountry: String,
    val editProfileUrl: String,
    val email: String?,
    val firstName: String,
    val genderPronoun: String,
    val id: String,
    val industrySelections: List<IndustrySelection>,
    val interests: List<Interest>,
    val isAdmin: Int,
    val jobs: List<Job>,
    val languages: List<Language>,
    val largePhotoUrl: String,
    val lastName: String,
    val lookingForSelections: List<LookingForSelection>,
    val maidenName: String?,
    val nationalities: List<Nationality>,
    val photoEditable: Int,
    val photoUrl: String,
    val school: String,
    val skills: List<String?>,
    val sports: List<String?>,
    val state: String?,
    val uid: String,
    val visitableProfile: Boolean,
    val workTitle: String?,
    val yearOfGraduationLookup: Int,
    val yearOfGraduationValue: String,
    val zip: String?
)