[versions]
agp = "9.0.0-alpha06"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.12.3"
androidx-lifecycle = "2.9.6"
autolinktext = "2.0.2"
coilCompose = "3.3.0"
compose-multiplatform = "1.10.0"
composeWebviewMultiplatform = "2.0.3"
datastore = "1.2.0"
datastorePreferences = "1.2.0"
kachetor = "1.1.0"
kotlin = "2.3.0"
kotlinxDatetime = "0.7.1"
ktorClientAndroid = "3.4.0"
lifecycle = "2.5.0"
material3 = "1.9.0"
qrose = "1.1.1"
securityCryptoKtx = "1.1.0"
uiTooling = "1.10.0"
uiToolingPreview = "1.10.0"
voyager = "1.1.0-beta03"
composeIcons = "1.1.1"
uiGraphicsAndroid = "1.10.2"
sqlDelight = "2.2.1"
koin-bom = "4.1.1"
[libraries]

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
autolinktext = { module = "sh.calvin.autolinktext:autolinktext", version.ref = "autolinktext" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
androidx-security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "securityCryptoKtx" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilCompose" }
compose-webview-multiplatform = { module = "io.github.kevinnzou:compose-webview-multiplatform", version.ref = "composeWebviewMultiplatform" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
jetbrains-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
kachetor = { module = "com.vipulasri.kachetor:kachetor", version.ref = "kachetor" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose =  { module = "io.insert-koin:koin-compose" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientAndroid" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientAndroid" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientAndroid" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientAndroid" }
lifecycle = { module = "com.arkivanov.essenty:lifecycle", version.ref = "lifecycle" }
qrose = { module = "io.github.alexzhirkevich:qrose", version.ref = "qrose" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "uiTooling" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screenmodel = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-tabNavigator = { module = "cafe.adriel.voyager:voyager-tab-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version = "1.1.0-beta03" }
fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", name = 'font-awesome', version.ref = "composeIcons" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
native-driver = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }