package org.swg.swiftgroups_app.CGAPI.EventAPI

import androidx.compose.runtime.MutableState
import kotlinx.serialization.Serializable

@Serializable
data class EventSpecificAPI(
    val attendees: List<Attendee>,
    val attendees_count: Int,
    val attending: String,
    val checkin_attendees: Int,
    val connections_more: Int,
    val display_map: Int,
    val edit_url: String,
    val event_date: String,
    val event_description: String,
    val event_display_list: String,
    val event_end_date: String,
    val event_end_time: String,
    val event_end_utc: String,
    val event_group: String,
    val event_group_id: Int,
    val event_header: String?,
    val event_id: Int,
    val event_name: String,
    val event_start_time: String,
    val event_start_utc: String,
    val event_tags: List<EventTag>,
    val event_timezone: String,
    val event_type: String,
    val friends_going: String?,
    val friends_more_going: Int,
    val html_description: String,
    val interested: Int,
    val isLive: Int,
    val isOnGoing: Int,
    val location: String,
    val manage: Int,
    val map_location: String,
    val notifications_status: Int,
    val pdfTicketsUrl: String?,
    val photoHeight: Int,
    val photo_url: String,
    val register_url: String,
    val register_url_web: String,
    val registered: Int,
    val registration_status: String,
    val share_url: String,
    val showRegisterButton: Int,
    val tickets: List<Ticket>?,
    val video_conferencing_link: String,
    val video_conferencing_type: String
)